table mart_customer_behavior
	lineageTag: 7d579a7c-2e5f-48a6-b7ff-df40afc87a97

	column customer_sk
		dataType: int64
		formatString: 0
		lineageTag: 6e48a08d-cb78-44be-b59a-b86ff70cf7b0
		summarizeBy: sum
		sourceColumn: customer_sk

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: bce4fecd-9b94-4c4b-a2ca-57aa6387d5f7
		summarizeBy: sum
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column revenue
		dataType: string
		lineageTag: 0c77d555-b366-44f2-840c-46e5004a6bcc
		summarizeBy: none
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

	column last_purchase_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: afe1d29b-c184-4f9b-8ba6-a1f39a237241
		summarizeBy: none
		sourceColumn: last_purchase_date

		variation Variation
			isDefault
			relationship: d84a5286-0337-4a01-a2e6-ed602e825578
			defaultHierarchy: LocalDateTable_11bdf458-afef-400f-8c28-705e804c4041.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column activity_status
		dataType: string
		lineageTag: 4189a4e6-b37c-42fb-81d5-804f7f855ded
		summarizeBy: none
		sourceColumn: activity_status

		annotation SummarizationSetBy = Automatic

	column revenue_segment
		dataType: string
		lineageTag: eae7d2c5-27f8-4103-952e-d46f6fd645fe
		summarizeBy: none
		sourceColumn: revenue_segment

		annotation SummarizationSetBy = Automatic

	partition mart_customer_behavior = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Al\Downloads\data-1785780632924.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Use First Row as Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Change Type" = Table.TransformColumnTypes(#"Use First Row as Headers",{{"customer_sk", Int64.Type}, {"customer_id", Int64.Type}, {"revenue", type text}, {"last_purchase_date", type date}, {"activity_status", type text}, {"revenue_segment", type text}})
				in
				    #"Change Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

