table mart_employee_performance
	lineageTag: 004fe4b3-3a20-46ca-9708-28a9719ed9fe

	column employee_sk
		dataType: int64
		formatString: 0
		lineageTag: 2424e68f-cdc9-4b47-bb67-df380a467ca4
		summarizeBy: sum
		sourceColumn: employee_sk

		annotation SummarizationSetBy = Automatic

	column employee_id
		dataType: int64
		formatString: 0
		lineageTag: e04a6320-ab2f-4c04-9674-7667079d3dee
		summarizeBy: sum
		sourceColumn: employee_id

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: dd4ef1ec-3ce9-4a9e-8dbc-2eb9ffe46ab0
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: 731cb2e3-6f1b-4a11-915a-b9c010f38a8b
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column revenue
		dataType: double
		lineageTag: 093226d5-be73-42ad-8d4d-17efef72892a
		summarizeBy: sum
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column quantity_sales
		dataType: int64
		formatString: 0
		lineageTag: 65b521d4-fc31-4ebf-8be8-fe2186ebf9ad
		summarizeBy: sum
		sourceColumn: quantity_sales

		annotation SummarizationSetBy = Automatic

	column count_sales
		dataType: int64
		formatString: 0
		lineageTag: 8fae4d3e-1640-4ec3-a8c5-2a1333f774b2
		summarizeBy: sum
		sourceColumn: count_sales

		annotation SummarizationSetBy = Automatic

	column employee_rank
		dataType: int64
		formatString: 0
		lineageTag: aee6cf4c-871e-47b1-a201-93458bde59f7
		summarizeBy: sum
		sourceColumn: employee_rank

		annotation SummarizationSetBy = Automatic

	partition mart_employee_performance = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Al\Downloads\data-1785780765765.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Use First Row as Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Change Type" = Table.TransformColumnTypes(#"Use First Row as Headers",{{"employee_sk", Int64.Type}, {"employee_id", Int64.Type}, {"first_name", type text}, {"last_name", type text}, {"revenue", type number}, {"quantity_sales", Int64.Type}, {"count_sales", Int64.Type}, {"employee_rank", Int64.Type}})
				in
				    #"Change Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

