table mart_daily_anomaly
	lineageTag: 074164e8-a90e-4eed-9c58-a3a08b031205

	measure 'Ожидаемая выручка (Цель)' =
			
			VAR PlanVal = SUM(mart_daily_anomaly[expected_revenue])
			VAR FactVal = SUM(mart_daily_anomaly[revenue])
			RETURN
			IF(
			    ISBLANK(PlanVal) || PlanVal = 0 || ISBLANK(FactVal),
			    BLANK(),
			    PlanVal
			)
		lineageTag: 1976e699-c415-4ca0-8fea-503c941d5dc4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column shop_sk
		dataType: int64
		formatString: 0
		lineageTag: d8ba994a-140d-434a-bb24-3a76870c8338
		summarizeBy: none
		sourceColumn: shop_sk

		annotation SummarizationSetBy = Automatic

	column full_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 94bf1a65-a80d-4de4-96d2-05e5e7b10259
		summarizeBy: none
		sourceColumn: full_date

		variation Variation
			isDefault
			relationship: baea1599-90c0-417e-854a-7c1961b73e68
			defaultHierarchy: LocalDateTable_301ae34e-7bcc-4622-a1ea-589b3ee1c2df.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column revenue
		dataType: double
		lineageTag: 5fe6740c-eab2-4d14-82dd-b342b58c5adc
		summarizeBy: sum
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column expected_revenue
		dataType: double
		lineageTag: 7da4034f-74e5-4981-afc9-f1aeb4fafde2
		summarizeBy: sum
		sourceColumn: expected_revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column uplift
		dataType: double
		lineageTag: a09c5d90-5780-4e41-afbc-d94d4182d473
		summarizeBy: sum
		sourceColumn: uplift

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Start of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ab6e7976-a292-4b87-a113-799ac17399fe
		summarizeBy: none
		sourceColumn: Start of Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition mart_daily_anomaly = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Al\Downloads\data-1785780683460.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Use First Row as Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Change Type" = Table.TransformColumnTypes(#"Use First Row as Headers",{{"shop_sk", Int64.Type}, {"full_date", type date}, {"revenue", type number}, {"expected_revenue", type text}, {"uplift", type text}}),
				    #"Inserted Start of Month" = Table.AddColumn(#"Change Type", "Start of Month", each Date.StartOfMonth([full_date]), type date),
				    #"Changed Type" = Table.TransformColumnTypes(#"Inserted Start of Month",{{"expected_revenue", type number}, {"uplift", type number}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",null,0,Replacer.ReplaceValue,{"expected_revenue"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,0,Replacer.ReplaceValue,{"uplift"})
				in
				    #"Replaced Value1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

